### ISSUE TITLE
Script to change user presence status

### ISSUE THREAD

**Issue by ThinkroSystem** [djabberd/DJabberd#29]
Hello, 

It may be the wrong place to ask, but i did not find other place.

Djabberd is a wonderful XMPP server, but i would like to be able to change the presence status of an user using a script. For example it could allow Asterisk to put [On the phone] prefix to the presence status. I've tried to search a solution, to understand the source code but i did not find a solution.

Could you help me ?

Thank you.

**Comment by rufferson** [comment]
to make it right you need use *'s xmpp plugin which will register a client session, bind a resource and handle sip2xmpp bridge. otherwise you'll need plugin to inject spoofed presence (for normal clients) but that may confuse/desync actual connected clients.
