### ISSUE TITLE
Question: how do I notify DJabberd that a user's Roster has changed?

### ISSUE THREAD

**Issue by akarelas** [djabberd/DJabberd#34]
Since there's no mailing list or IRC channel for DJabberd, I'm writing my question here.

I have my users' friends lists in a database table, which I update with an external script. My question is: How can this external script notify DJabberd that a new friendship has popped into existence, so that DJabberd can update the Jabber clients?

Does DJabberd have an external interface for tasks like this?

**Comment by rufferson** [comment]
Sorry to necro-notification but I'm going to close this one.
There's no out of the box functionality of course, but one can write own roster storage plugin which may use say a flag field in DB to mark a new item, a timer to check for new items, and then run either RosterAddUpdateItem or RosterRemoveItem hooks which will pushing a roster update to the connected affected users. And then drop the flag. You'd need to watch for recursion - the hook calls roster storage which supposed to commit new roster to the storage and call `done` which actually pushes the roster update. As you're commiting roster update out of band you'd need to skip that and just call done for recursive call, and actually commit the change for non-recursive (inband update).
