### ISSUE TITLE
XEPs and RFCs support page with version

### ISSUE THREAD

**Issue by Neustradamus** [djabberd/DJabberd#38]
It is possible to have a XEPs and RFCs support page with version (XEP-XXXX v1.2)?

Examples:
- https://metronome.im/supported-xeps-list
- https://dev.gajim.org/gajim/gajim/wikis/help/gajimxepsupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by apparentlymart** [comment]
There is a page for this on our old, and generally abandoned wiki: http://djabberd.pbworks.com/w/page/10247069/Standards%20Support

As far as I know, the situation has not changed since that page was last updated.

**Comment by Neustradamus** [comment]
Thanks @apparentlymart :)
Hope help for new devs one day, for an update (RFCs and XEPs) and for have a next doc with version...
All plugins are not here on https://github.com/djabberd/ ?

20180317 : http://djabberd.pbworks.com/w/page/10247069/Standards%20Support
RFC-3920: XMPP Core 	 
RFC-3921: XMPP IM and Presence 	 
XEP-0030: Service Discovery -> Basic support built in; can be extended by plugins.
XEP-0045: Multi-User Chat -> Basic support via DJabberd::MUC plugin.
XEP-0049: Private XML Storage -> Via DJabberd::Plugin::PrivateStorage plugin.
XEP-0077: In-Band Registration -> Via hooks; Supported by some Authentication providers.
XEP-0092: Software Version -> Via DJabberd::Plugin::JabberIqVersion plugin.
XEP-0199: XMPP Ping -> Via DJabberd::Plugin::Ping plugin.
XEP-0202: Entity Time -> Via DJabberd::EntityTime plugin.

**Comment by rufferson** [comment]
You can take a look here also
https://github.com/rufferson/DJabberd/wiki/XEP-Coverage
But that's a fork, since no PRs are accepted it's unlikely to land in the master

**Comment by Neustradamus** [comment]
@rufferson Whaouuuu always a development on DJabberd! :)

For the wiki page, can you add XEP version? Example: XEP-0045 v1.2
And XMPP RFCs too because there are difference between old and new...

Look all forks for integrate all not integrated commits!
Examples:
- https://github.com/fastmailops/DJabberd
- https://github.com/fastmailops/djabberd-privatestorage
- https://github.com/fastmailops/djabberd-offlinestorage

In more XMPP Compliance Suites: https://github.com/djabberd/DJabberd/issues/37
I have added a ticket for an important part: SCRAM: https://github.com/djabberd/DJabberd/issues/40

**Comment by rufferson** [comment]
RFC Coverage is more or less described on the [landing page](https://github.com/rufferson/DJabberd/wiki).

I did review fastmailops fork earlier and some I've already implemented differently by that time and others without context I don't see what exactly they are trying to solve.

XEP Version is a good hint btw, need to add. Perhaps rather namespace as there could be minor xep reviews without namespace bump.

**Comment by Neustradamus** [comment]
This page needs to be updated ^^

And really look changes between old RFCs and new...
RFC6120: https://tools.ietf.org/html/rfc6120#appendix-D
RFC6121: https://tools.ietf.org/html/rfc6121#appendix-E
RFC6122: https://tools.ietf.org/html/rfc6122#appendix-C
RFC7622: https://tools.ietf.org/html/rfc7622#appendix-A

Look all XMPP RFCs: https://github.com/xsf/xmpp.org/issues/414

**Comment by rufferson** [comment]
Yes the statement in core support section is based on those appendices, with clarification below what is there and what is missing. Feel free to send me required markdown changes :)
Perhaps better will be just to run compliance test and provide the results. As for instance StartTLS patches allowed me to hit A/A grades on IM Observatory ![badge](https://xmpp.net/badge.php?domain=ruff.mobi).

**Comment by Neustradamus** [comment]
What is the tested server?

**Comment by rufferson** [comment]
my [home server](https://xmpp.net/result.php?domain=ruff.mobi&type=client) running djabberd 0.86+ (from my forked branch) - that actually the main driver behind my motivation, to make djabberd secure and compliant modern xmpp server. the only missing piece though is MUC as I don't do group chats with my family. So MIX is somewhere at the bottom of TODO list.

**Comment by Neustradamus** [comment]
@rufferson:

About XMPP RFCs:
- https://tools.ietf.org/html/rfc3920 -> https://tools.ietf.org/html/rfc6120 to https://tools.ietf.org/html/rfc7590
- https://tools.ietf.org/html/rfc3921 -> https://tools.ietf.org/html/rfc6121
- https://tools.ietf.org/html/rfc3922
- https://tools.ietf.org/html/rfc3923
- https://tools.ietf.org/html/rfc4622 -> https://tools.ietf.org/html/rfc5122
- https://tools.ietf.org/html/rfc6122 -> https://tools.ietf.org/html/rfc7622
- https://tools.ietf.org/html/rfc7711
- https://tools.ietf.org/html/rfc7712
- https://tools.ietf.org/html/rfc7395

Difference noted in RFCs:
- https://tools.ietf.org/html/rfc6120#appendix-D
- https://tools.ietf.org/html/rfc6121#appendix-E
- https://tools.ietf.org/html/rfc6122#appendix-C
- https://tools.ietf.org/html/rfc7622#appendix-A

Note:
- http://jabber.996255.n3.nabble.com/Changes-missing-from-RFC-6120-s-Differences-from-RFC-3920-td30486.html

**Comment by rufferson** [comment]
This is exactly what I mean, you cannot introduce breaking changes in RFC (non-errata) - you need to make a new RFC which will obsolete (or correct semantic) of the other one. So saying we support RFC6121 means exactly that, regardless of its revision. The correction like in RFC7590 (and others, like nodeprep) are correcting behaviour of specific subsystem or interaction with other protocols/standards.
Same stands for xeps, except they differentiate semantic (specified by namespace) and subsystem (specified by xep number).

**Comment by rufferson** [comment]
I've updated wiki with RFC and XEP coverage, feel free to correct it where/as appropriate

**Comment by Neustradamus** [comment]
@rufferson: Thanks for https://github.com/djabberd/DJabberd/wiki/XEP-Coverage!

Like I have specified in the main text, the problem is that there is not the version of XEPs...
Example: XEP-XXXX v1.2

The goal is to do a state of play which will be necessary to easy update.

Please remove the old: https://github.com/rufferson/DJabberd/wiki/XEP-Coverage

**Comment by Neustradamus** [comment]
@rufferson:

RFC3920 -> RFC6120
- https://tools.ietf.org/tools/rfcdiff/rfcdiff.pyht?url1=https://www.ietf.org/rfc/rfc3920.txt&url2=https://www.ietf.org/rfc/rfc6120.txt

RFC3921 -> RFC6121
- https://tools.ietf.org/tools/rfcdiff/rfcdiff.pyht?url1=https://www.ietf.org/rfc/rfc3921.txt&url2=https://www.ietf.org/rfc/rfc6121.txt

Draft but Very Important:
- https://tools.ietf.org/html/draft-cridland-xmpp-session-01
