### ISSUE TITLE
wrong stanza set for s2s outgoing messages

### ISSUE THREAD

**Issue by discordianfish** [djabberd/DJabberd#4]
djabberd sets per default jabber:client as xmlns, but I must be jabber:server.
This renders djabberd useless for talking to, for example, jabber.org users because there jabberd is pretty picky about that.

I have a small fix for that. There might be a better approach, but this is the best I come up so far:

<pre>
   diff --git a/lib/DJabberd/Delivery/S2S.pm b/lib/DJabberd/Delivery/S2S.pm
   index c866b2b..e447703 100644
   --- a/lib/DJabberd/Delivery/S2S.pm
   +++ b/lib/DJabberd/Delivery/S2S.pm
   @@ -35,6 +35,7 @@ sub deliver {
            return $cb->declined;
        }
    
   +    $stanza->set_xmlns('jabber:server');
        $logger->debug("s2s delivery attempt for $to");
    
        # FIXME: let get_conn_for_domain return an error code or something
   diff --git a/lib/DJabberd/Stanza.pm b/lib/DJabberd/Stanza.pm
   index 521fbdf..2b53e8a 100644
   --- a/lib/DJabberd/Stanza.pm
   +++ b/lib/DJabberd/Stanza.pm
   @@ -135,6 +135,11 @@ sub set_to {
        $self->{attrs}{"{}to"} = ref $_[1] ? $_[1]->as_string : $_[1];
    }
    
   +sub set_xmlns {
   +    my DJabberd::Stanza $self = $_[0];
   +    $self->{attrs}{"{}xmlns"} = $_[1];
   +}
   +
    sub deliver_when_unavailable {
        0;
    }
</pre>

**Comment by discordianfish** [comment]
Hahaha @dominikschulz plz review! Just realized you worked on this project :)

**Comment by dominikschulz** [comment]
LGTM. Why don't you open a PR?

**Comment by rufferson** [comment]
There is $stanza->replace_ns("jabber:server", "jabber:client"); call in lib/DJabberd/Delivery/Local.pm
I suggest making similar in Delivery/S2S.

**Comment by discordianfish** [comment]
Well this was more a joke than a serious contribution that would warrant me looking into the travis issues, so 👋

**Comment by Neustradamus** [comment]
@rufferson: It has been solved?

**Comment by rufferson** [comment]
No, it's still sending jabber:client xmlns. Mainly because I've never faced with any problem with that yet. 
Which doesn't mean the problem doesn't exist of course, will add a patch
