### ISSUE TITLE
Failed to load plugin DJabberd::SASL::AuthenSASL: Can't use 'defined(%hash)

### ISSUE THREAD

**Issue by carnotweat** [djabberd/DJabberd#41]
Possible precedence issue with control flow operator at lib/DJabberd/Connection.pm line 263.Possible precedence issue with control flow operator at lib/DJabberd/Connection.pm line 274.Configuration error on line 29: Failed to load plugin DJabberd::SASL::AuthenSASL: Can't use 'defined(%hash)' (Maybe you should just omit the defined()?) at lib/DJabberd/SASL.pm line 33, <$fh> line 1.

**Comment by rufferson** [comment]
yes almost every fork around is fixing these deprecations, feel free to do as interpreter advices.
